### ISSUE TITLE
Windows' PATH is not appended

### ISSUE THREAD

**Issue by fauzie811** [yuk7/AlpineWSL#10]
Windows' PATH environment variable is not appended to the WSL. "append-path" is already set to "on".

![Annotation 2019-10-03 212621](https://user-images.githubusercontent.com/318095/66135997-f713ec80-e624-11e9-896c-35dd59e90809.jpg)

**Comment by yuk7** [comment]
It seems reset PATH in /etc/profile.
Please delete
```
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
line in /etc/profile.

**Comment by yuk7** [comment]
This is marked as bug.
I'll fix it.
Thanks.

**Comment by yuk7** [comment]
I released new release included fixes this.

**Comment by dazoe** [comment]
That new release is copying the profile from the host's /etc directory and so is getting a profile that does not work very well

**Comment by yuk7** [comment]
Oops! Thank you.

**Comment by bergkvist** [comment]
The Windows PATH (with .exe-files) doesn't seem to be included for me when I first install Alpine in WSL2.

I ended up starting ubuntu2004 (which had the correct windows paths in the PATH variable, formatted correctly) and copy-pasting the windows related path-directories into `~/.profile` in Alpine.

```
        ................           root@DESKTOP-ABCDEFG
       ∴::::::::::::::::∴          OS: Alpine Linux (on the Windows Subsystem for Linux)
      ∴::::::::::::::::::∴         Kernel: x86_64 Linux 4.19.84-microsoft-standard
     ∴::::::::::::::::::::∴        Uptime: 13m
    ∴:::::::. :::::':::::::∴       Packages: 118
   ∴:::::::.   ;::; ::::::::∴      Shell: ash
  ∴::::::;      ∵     :::::::∴     Disk:  /  ()
 ∴:::::.     .         .::::::∴    CPU: Intel Core i7-6700K @ 8x 4.008GHz
 ::::::     :::.    .    ::::::    RAM: 3113MiB / 25597MiB
 ∵::::     ::::::.  ::.   ::::∵   
  ∵:..   .:;::::::: :::.  :::∵    
   ∵::::::::::::::::::::::::∵     
    ∵::::::::::::::::::::::∵      
     ∵::::::::::::::::::::∵       
      ::::::::::::::::::::        
       ∵::::::::::::::::∵ 
```
