### ISSUE TITLE
what's the password?

### ISSUE THREAD

**Issue by ghost** [yuk7/AlpineWSL#11]
It's not my windows login password.  I basically have one account with no permissions and no way to install software I can see.

**Comment by yuk7** [comment]
No password has been set.
Use `passwd` command to set a password.

**Comment by ghost** [comment]
That doesn't work though, as your current user has no password when you start up.

I had to follow the instructions here:

https://winaero.com/blog/reset-password-wsl-linux-distro-windows-10/

**Comment by yuk7** [comment]
Solved?
