### ISSUE TITLE
[question] upgrade

### ISSUE THREAD

**Issue by GuillaumeBibaut** [yuk7/AlpineWSL#14]
Hello, I'm wondering if there is an easy way to upgrade an already install version of your project?

It seems I've installed version 3.11.3, and I would like to upgrade to 3.11.5.

**Comment by yuk7** [comment]
Please do these

1. Launcher Update:
Please overwrite the exe.

2. System Upgrade:
https://wiki.alpinelinux.org/wiki/Upgrading_Alpine#Upgrading_to_latest_release
