### ISSUE TITLE
AlpineWSL vs WSL-DistroLauncher-Alpine

### ISSUE THREAD

**Issue by dave-kennedy** [yuk7/AlpineWSL#15]
I'm just curious, what's the difference between this and the app in the Windows Store, the source for which is [here](https://github.com/agowa338/WSL-DistroLauncher-Alpine)?

**Comment by yuk7** [comment]
AlpineWSL uses wsldl which has more features in the launcher.
This allows you to easily install multiple Alpine instances with the name you specify.
This is useful for building multiple test environments.

WSL-DistroLauncher-Alpine is distributed by AppX, so it can be used as a Windows store application.


AlpineWSL source is here:
https://github.com/yuk7/AlpineWSL/blob/master/Makefile
https://github.com/yuk7/wsldl/
