### ISSUE TITLE
HRESULT:0x80070003 error

### ISSUE THREAD

**Issue by rtpm** [yuk7/AlpineWSL#2]
Hello,
I am getting error HRESULT:0x80070003 when trying to run Alpine.exe without arguments.

Have WSL installed and running ubuntu on top without problems.

Thanks

**Comment by yuk7** [comment]
@btmichalowic 
Thank you for reporting!
I don't know about this issue, But could you try this:
1. WSL is can install in C: drive only. Please check path.
2. Unblock download files.(https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile/)

Please give me additional information if not resolved...

**Comment by rtpm** [comment]
WSL is running on c: drive. At the moment, Debian from MS Store running without any problems (before I was using Ubuntu).

I download the Alpine.zip file (5,7 MB) and extract. When running the extracted Alpine.exe without any parameters I get:

R:\Alpine1>Alpine.exe
Installing...
ERROR:Installation Failed!
HRESULT:0x80070003
Press any key to continue...

R:\Alpine1>

The same goes for running privileged (cmd -> run as admin) mode and non privileged mode.

There's a smilar problem at: https://github.com/DDoSolitary/LxRunOffline/issues/10

My windows version: 1709, compilation 16299.248

Thanks

**Comment by yuk7** [comment]
@rtpm 
Please extract Alpine.zip to C: drive...
Probably,This issue can solved.

**Comment by rtpm** [comment]
Running Alpine.exe from c: drive worked like a charm.

Thank You!

**Comment by yuk7** [comment]
OK!
I'll close this issue
