### ISSUE TITLE
Outdated AlpineWSL release

### ISSUE THREAD

**Issue by boyedarat** [yuk7/AlpineWSL#27]
The latest AlpineLinux release is 3.16.0: https://www.alpinelinux.org/posts/Alpine-3.16.0-released.html
The latest WSLDL release is 22020900: https://github.com/yuk7/wsldl/releases

Could we have updated AlpineWSL release packages to the latest above versions?
Thanks.

**Comment by yuk7** [comment]
Ah, Thanks for remind.
I'll update it

**Comment by yuk7** [comment]
updated

**Comment by soulspark666** [comment]
@yuk7 can you instead add
```
http://dl-3.alpinelinux.org/alpine/latest-stable/main
http://dl-3.alpinelinux.org/alpine/latest-stable/community
```
in the `/etc/apk/repositories`
https://wiki.alpinelinux.org/wiki/Upgrading_Alpine
