### ISSUE TITLE
Cannot install unless ran as elevated

### ISSUE THREAD

**Issue by SunbrightShinobi** [yuk7/AlpineWSL#6]
So this used to work fine and not sure if it was a windows patch or what but now you 10102700 release will not install unless ran as administrator. To make sure it wasn't a gpo or something. I used the latest Ubuntu from Store "CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2018.817.0_x64__79rhkp1fndgsc", download and extracted and ran exe and it install as normal user with no issues.

Running Windows 10 Enterprise v1709 16299.847

**Comment by yuk7** [comment]
Please check directory owner and access privileges.
Installation with administrator privileges may cause problems...

**Comment by yuk7** [comment]
Please check directory owner and access permissions...

**Comment by SunbrightShinobi** [comment]
So I tested this with your arch build and arch works just fine repeating the exact same steps and same installer location

**Comment by SunbrightShinobi** [comment]
Upgrading to launcher 18122700 corrected the issue. https://github.com/yuk7/AlpineWSL/commit/18d10f162a3af23a054231327d8f77a2b7aef27c
