### ISSUE TITLE
Setting current directory of Visual Studio Code

### ISSUE THREAD

**Issue by cbettinger** [yuk7/AlpineWSL#8]
I really love Alpine Linux, especially within WSL. I want to use it as the integrated terminal within Visual Studio Code. Setting that within settings.json works fine:
```
{
   "terminal.integrated.shell.windows": "C:\\Program Files\\Alpine\\Alpine.exe",
   ...
}
```
The problem is that Alpine sets the current directory to the home directory. The Ubuntu WSL starts on the current project's root directory when used as a integrated terminal in VS Code.

Is there a way to set the current directory manually or - even better - to behave like the Ubuntu WSL?

**Comment by yuk7** [comment]
Please use "run" argument,that inherit current directory.
ex:Please add this to VSCode's settings.json:
```
"terminal.integrated.shellArgs.windows": ["run"]
```

**Comment by cbettinger** [comment]
That works simply perfect! Thank you very much.
